export const types = {
  Fire: { name: "Feu", color: "#B92623" },
  Flying: { name: "Vol", color: "#507089" },
  Electric: { name: "Electrik", color: "#E6E800" },
  Bug: { name: "Insecte", color: "#135128   " },
  Rock: { name: "Roche", color: "#4F1B03" },
  Ground: { name: "Sol", color: "#B27928f" },
  Steel: { name: "Acier", color: "#638076" },
  Ghost: { name: "Spectre", color: "#373579" },
  Fighting: { name: "Combat", color: "#A64A24" },
  Dark: { name: "Ténèbre", color: "black" },
  Psychic: { name: "Psy", color: "#B6287B" },
  Ice: { name: "Glace", color: "#89D6F7" },
  Dragon: { name: "Dragon", color: "#43939E" },
  Water: { name: "Eau", color: "#0E55F2" },
  Grass: { name: "Plante", color: "#078740" },
  Normal: { name: "Normal", color: "#7F5C64" },
  Poison: { name: "Poison", color: "#692E95" },
  Fairy: { name: "Fée", color: "pink" },
};
